/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calar.gui;

import com.calar.logic.Product;
import com.calar.logic.User;
import com.calar.logic.Validations;
import com.calar.persistence.ConnectionDB;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ivanfriasgil
 */
public class AddExistencias extends javax.swing.JFrame {
    
    private User user;
    private Product product;
    /**
     * Creates new form AddProduct
     */
    public AddExistencias(User user) {
        this.user = user;
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        nombreField = new javax.swing.JTextField();
        cantidad = new javax.swing.JLabel();
        cantidadField = new javax.swing.JTextField();
        precio = new javax.swing.JLabel();
        precioField = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        concepto = new javax.swing.JLabel();
        conceptoField = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nombreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cantidad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidad.setText("Cantidad producto");

        cantidadField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cantidadField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        precio.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        precio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio.setText("Precio total");

        precioField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        precioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        add.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        add.setText("Añadir");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        concepto.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        concepto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        concepto.setText("Concepto gasto");

        conceptoField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        conceptoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nombre.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre producto");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conceptoField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(concepto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conceptoField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String nombreProducto = nombreField.getText();
        String precioTotal = precioField.getText();
        String cantidad = cantidadField.getText();
        String concepto = conceptoField.getText();
        String user_idProducto = user.getEmail();
     
        // Validamos todo para poder hacer las conversiones.
        if (Validations.validateName(nombreProducto) && Validations.validateSendPrice(precioTotal) && Validations.validateNum(cantidad)){
            float precioTotalFloat = Float.parseFloat(precioTotal);
            int cantidadInt = Integer.parseInt(cantidad);
            
            // Si el producto existe nos retorna true, por lo tanto podemos seguir.
            
            if (ConnectionDB.checkProductExists(nombreProducto, user.getEmail())){
                // Añadimos a la tabla gastos el gasto para crear una nueva línea.
                ConnectionDB.addGasto(user.getEmail(), cantidadInt, precioTotalFloat, concepto);
                // Añadimos las existencias al producto productos.
                ConnectionDB.updateProductExistencias(user.getEmail(), nombreProducto, cantidadInt);

                JOptionPane.showMessageDialog(null, "Gasto y existencias añadidas correctamente.");  
            } else {
                JOptionPane.showMessageDialog(null, "El producto que intentas pedir no existe para este usuario.");
            }
             
        } else {
            JOptionPane.showMessageDialog(null, "Error al introducir los datos.");
        }  
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel cantidad;
    private javax.swing.JTextField cantidadField;
    private javax.swing.JLabel concepto;
    private javax.swing.JTextField conceptoField;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreField;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField precioField;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
